version: '2'

services:
  dev:
    build:
      context:  ./
      dockerfile: Dockerfile.dev
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/

  stable:
    build:
      context: ./
      dockerfile: Dockerfile.stable
