version: '2'

services:
  dev:
    build:
      context:  ./
      dockerfile: Dockerfile.dev
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    working_dir: ${PWD}

  debug:
    build:
      context:  ./
      dockerfile: Dockerfile.dev
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    environment:
      - PANOPTES_DEBUG=true
    working_dir: ${PWD}

  stable:
    build:
      context: ./
      dockerfile: Dockerfile.stable
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    working_dir: ${PWD}

  dev2:
    build:
      context:  ./
      dockerfile: Dockerfile.dev2
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    working_dir: ${PWD}

  debug2:
    build:
      context:  ./
      dockerfile: Dockerfile.dev2
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    environment:
      - PANOPTES_DEBUG=true
    working_dir: ${PWD}

  stable2:
    build:
      context: ./
      dockerfile: Dockerfile.stable2
    volumes:
      - ${HOME}/.panoptes/:/root/.panoptes/
      - ${HOME}:${HOME}
    working_dir: ${PWD}
